name: Build TIPA Packages

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          sudo git clone --recursive https://github.com/theos/theos.git /var/theos
          echo "THEOS=/var/theos" >> $GITHUB_ENV

      - name: Download & Install iOS 16.5 SDK
        run: |
          mkdir -p $THEOS/sdks
          curl -L -o iPhoneOS16.5.sdk.tar.xz https://github.com/sbingner/sdk-possibly-patched/raw/master/iPhoneOS16.5.sdk.tar.xz
          tar -xf iPhoneOS16.5.sdk.tar.xz -C $THEOS/sdks/
          rm iPhoneOS16.5.sdk.tar.xz

      - name: Run Build Script
        run: |
          rm -rf dist
          mkdir dist

          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=
          cp -p "`ls -dtr1 packages/* | tail -1`" ./dist/

          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless PACKAGE_TIPA=1
          cp -p "`ls -dtr1 packages/* | tail -1`" ./dist/

          if [ -f TrollDecrypt.tipa ]; then
            cp -p TrollDecrypt.tipa ./dist/
          else
            echo "Warning: TrollDecrypt.tipa not found, skipping..."
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tipa-dist-packages
          path: dist/
