name: Build TIPA Packages

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          echo "THEOS=$HOME/theos" >> $GITHUB_ENV

      - name: Download & Install iOS 16.5 SDK
        run: |
          mkdir -p $THEOS/sdks
          git clone --depth 1 --filter=blob:none --sparse https://github.com/theos/sdks.git $THEOS/sdks-tmp
          cd $THEOS/sdks-tmp
          git sparse-checkout set iPhoneOS16.5.sdk
          mv iPhoneOS16.5.sdk $THEOS/sdks/
          cd $HOME && rm -rf $THEOS/sdks-tmp

      - name: Run Build Script
        run: |
          rm -rf dist
          mkdir dist

          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=
          cp -p "`ls -dtr1 packages/* | tail -1`" ./dist/

          make clean
          make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless PACKAGE_TIPA=1
          cp -p "`ls -dtr1 packages/* | tail -1`" ./dist/

          if [ -f TrollDecrypt.tipa ]; then
            cp -p TrollDecrypt.tipa ./dist/
          else
            echo "Warning: TrollDecrypt.tipa not found, skipping..."
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tipa-dist-packages
          path: dist/
